#!/usr/bin/env bash
set -e
# Create/refresh PATH link after install/upgrade
ln -sf /opt/s3-jsync/bin/s3-jsync /usr/bin/s3-jsync || true

# Keep jpackage's desktop entry behavior, in case it's not added automatically
if command -v xdg-desktop-menu >/dev/null 2>&1; then
  xdg-desktop-menu install /opt/s3-jsync/lib/s3-jsync-s3-jsync.desktop || true
fi
